package AppModule.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Sep 23 17:41:56 IST 2017
// ---------------------------------------------------------------------
public interface applicationAM extends ApplicationModule {
    void refreshApplication();
}
