package AppModule.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Sep 13 16:57:50 IST 2017
// ---------------------------------------------------------------------
public interface payCertAM extends ApplicationModule {
    void createNewCertification();

    void refreshCertification();
}
