package AppModule.client;

import AppModule.common.applicationAM;

import oracle.jbo.client.remote.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Sep 23 17:41:56 IST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class applicationAMClient extends ApplicationModuleImpl implements applicationAM {
    /**
     * This is the default constructor (do not remove).
     */
    public applicationAMClient() {
    }

    public void refreshApplication() {
        Object _ret =
            this.riInvokeExportedMethod(this,"refreshApplication",null,null);
        return;
    }
}
